
package com.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientDetailSoap", targetNamespace = "http://soap.com/", wsdlLocation = "http://user-pc:8282/EyeCare/PatientDetailSoap?wsdl")
public class PatientDetailSoap_Service
    extends Service
{

    private final static URL PATIENTDETAILSOAP_WSDL_LOCATION;
    private final static WebServiceException PATIENTDETAILSOAP_EXCEPTION;
    private final static QName PATIENTDETAILSOAP_QNAME = new QName("http://soap.com/", "PatientDetailSoap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://user-pc:8282/EyeCare/PatientDetailSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PATIENTDETAILSOAP_WSDL_LOCATION = url;
        PATIENTDETAILSOAP_EXCEPTION = e;
    }

    public PatientDetailSoap_Service() {
        super(__getWsdlLocation(), PATIENTDETAILSOAP_QNAME);
    }

    public PatientDetailSoap_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTDETAILSOAP_QNAME, features);
    }

    public PatientDetailSoap_Service(URL wsdlLocation) {
        super(wsdlLocation, PATIENTDETAILSOAP_QNAME);
    }

    public PatientDetailSoap_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTDETAILSOAP_QNAME, features);
    }

    public PatientDetailSoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientDetailSoap_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PatientDetailSoap
     */
    @WebEndpoint(name = "newPort")
    public PatientDetailSoap getNewPort() {
        return super.getPort(new QName("http://soap.com/", "newPort"), PatientDetailSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PatientDetailSoap
     */
    @WebEndpoint(name = "newPort")
    public PatientDetailSoap getNewPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.com/", "newPort"), PatientDetailSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTDETAILSOAP_EXCEPTION!= null) {
            throw PATIENTDETAILSOAP_EXCEPTION;
        }
        return PATIENTDETAILSOAP_WSDL_LOCATION;
    }

}
