
package com.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PatientDetailSoap", targetNamespace = "http://soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PatientDetailSoap {


    /**
     * 
     * @return
     *     returns java.util.List<com.soap.PatientDetails>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPatientDetails", targetNamespace = "http://soap.com/", className = "com.soap.GetAllPatientDetails")
    @ResponseWrapper(localName = "getAllPatientDetailsResponse", targetNamespace = "http://soap.com/", className = "com.soap.GetAllPatientDetailsResponse")
    @Action(input = "http://soap.com/PatientDetailSoap/getAllPatientDetailsRequest", output = "http://soap.com/PatientDetailSoap/getAllPatientDetailsResponse")
    public List<PatientDetails> getAllPatientDetails();

}
