
package com.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OtherHospital", targetNamespace = "http://soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OtherHospital {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookAppointment", targetNamespace = "http://soap.com/", className = "com.soap.BookAppointment")
    @ResponseWrapper(localName = "bookAppointmentResponse", targetNamespace = "http://soap.com/", className = "com.soap.BookAppointmentResponse")
    @Action(input = "http://soap.com/OtherHospital/bookAppointmentRequest", output = "http://soap.com/OtherHospital/bookAppointmentResponse")
    public String bookAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
