
package com.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OtherHospitalService", targetNamespace = "http://soap.com/", wsdlLocation = "http://user-pc:8282/EyeCareClient/OtherHospitalService?wsdl")
public class OtherHospitalService
    extends Service
{

    private final static URL OTHERHOSPITALSERVICE_WSDL_LOCATION;
    private final static WebServiceException OTHERHOSPITALSERVICE_EXCEPTION;
    private final static QName OTHERHOSPITALSERVICE_QNAME = new QName("http://soap.com/", "OtherHospitalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://user-pc:8282/EyeCareClient/OtherHospitalService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OTHERHOSPITALSERVICE_WSDL_LOCATION = url;
        OTHERHOSPITALSERVICE_EXCEPTION = e;
    }

    public OtherHospitalService() {
        super(__getWsdlLocation(), OTHERHOSPITALSERVICE_QNAME);
    }

    public OtherHospitalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OTHERHOSPITALSERVICE_QNAME, features);
    }

    public OtherHospitalService(URL wsdlLocation) {
        super(wsdlLocation, OTHERHOSPITALSERVICE_QNAME);
    }

    public OtherHospitalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OTHERHOSPITALSERVICE_QNAME, features);
    }

    public OtherHospitalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OtherHospitalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OtherHospital
     */
    @WebEndpoint(name = "OtherHospitalPort")
    public OtherHospital getOtherHospitalPort() {
        return super.getPort(new QName("http://soap.com/", "OtherHospitalPort"), OtherHospital.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OtherHospital
     */
    @WebEndpoint(name = "OtherHospitalPort")
    public OtherHospital getOtherHospitalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.com/", "OtherHospitalPort"), OtherHospital.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OTHERHOSPITALSERVICE_EXCEPTION!= null) {
            throw OTHERHOSPITALSERVICE_EXCEPTION;
        }
        return OTHERHOSPITALSERVICE_WSDL_LOCATION;
    }

}
